import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131315",
        surface: "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1b1b1d",
        "surface-container": "#1f1f21",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-variant": "#353437",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#d0c5af",
        "on-background": "#e5e1e4",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#303032",
        outline: "#99907c",
        "outline-variant": "#4d4635",
        "surface-tint": "#e9c349",
        primary: "#f2ca50",
        "on-primary": "#3c2f00",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        secondary: "#ffb785",
        "on-secondary": "#502500",
        "secondary-container": "#db7620",
        "on-secondary-container": "#461f00",
        "secondary-fixed": "#ffdcc6",
        "secondary-fixed-dim": "#ffb785",
        tertiary: "#a0dda0",
        "on-tertiary": "#003910",
        "tertiary-container": "#85c186",
        error: "#ffb4ab",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-lg": "2rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        margin: "2rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "3.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "Playfair Display", "serif"],
        sans: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["var(--font-playfair)", "serif"],
        "headline-xl": ["var(--font-playfair)", "serif"],
        "headline-lg": ["var(--font-playfair)", "serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "headline-sm": ["var(--font-playfair)", "serif"],
        "price-display": ["var(--font-playfair)", "serif"],
        "body-lg": ["var(--font-jakarta)", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "sans-serif"],
        "body-sm": ["var(--font-jakarta)", "sans-serif"],
        "label-caps": ["var(--font-jakarta)", "sans-serif"],
        "label-md": ["var(--font-jakarta)", "sans-serif"],
        "label-sm": ["var(--font-jakarta)", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" }],
        "price-display": ["22px", { lineHeight: "26px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.14em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      boxShadow: {
        gold: "0 4px 24px rgba(212, 175, 55, 0.22), 0 1px 2px rgba(0, 0, 0, 0.8)",
        "gold-sm": "0 2px 10px rgba(242, 202, 80, 0.25)",
        card: "0 12px 32px -8px rgba(0, 0, 0, 0.65), 0 2px 6px rgba(0, 0, 0, 0.4)",
      },
    },
  },
  plugins: [],
};

export default config;

